# Compose File Version
version: "3.6"

services:
  app:
    image: chrisbouchard/discord-fate-bot:$VERSION
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      DFB_BOT_TOKEN_FILE: /run/secrets/token
      DFB_MONGO_CONNECTION_URL: mongodb://root@mongo:27017
      DFB_MONGO_PASSWORD_FILE: /run/secrets/mongo-password
    networks:
      - internal
    secrets:
      - source: discord-fate-bot-mongo-password
        target: mongo-password
      - source: discord-fate-bot-token
        target: token

  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-password
    networks:
      - internal
    secrets:
      - source: discord-fate-bot-mongo-password
        target: mongo-password
    volumes:
      - type: volume
        source: discord-fate-bot-mongo-data
        target: /data/db

networks:
  internal:
    driver: overlay

secrets:
  discord-fate-bot-mongo-password:
    external: true
  discord-fate-bot-token:
    external: true

volumes:
  discord-fate-bot-mongo-data:
    external: true

